# Generated by Django 5.1.2 on 2024-10-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='cluped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
