# Generated by Django 5.1.2 on 2024-10-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_alter_plot_plot_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='coverd_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
