# Generated by Django 5.1.2 on 2024-11-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_plot_coverd_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='id',
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
