# Generated by Django 5.1.2 on 2024-11-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0005_remove_plot_id_alter_plot_plot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
