# Generated by Django 5.1.2 on 2024-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0006_alter_plot_created_at_alter_plot_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='as_bifurcate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
