# Generated by Django 5.1.2 on 2024-11-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0007_plot_as_bifurcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255, unique=True)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('industrial_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commercial_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('infrastructure_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('year_of_development', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='technical.zone'),
        ),
    ]
